import type { Review, Product, Influencer, Competitor, SocialPost, Notification, AIRecommendation } from './types'

export const reviews: Review[] = [
  {
    id: '1',
    customerName: 'Sophia Chen',
    customerAvatar: '',
    initials: 'SC',
    product: 'Power Mist - Wild Watermelon',
    platform: 'Sephora',
    country: 'United States',
    rating: 5,
    date: '2024-01-15',
    text: "This is literally the best hand sanitizer I've ever used! The Wild Watermelon scent is absolutely divine. It dries so fast and leaves my hands feeling soft instead of dry and cracked. I've already bought 5 bottles for my friends and family. The packaging is beautiful too — it looks so chic on my desk.",
    aiSummary: 'Extremely positive review highlighting scent, fast-drying formula, moisturizing effect, and aesthetic packaging. Strong brand advocate.',
    emotion: 'Excited',
    sentiment: 'Positive',
    suggestedResponse: "Thank you so much, Sophia! 🍉 We're thrilled Wild Watermelon has become your favorite. Your enthusiasm means everything to us — and your friends are lucky to have such a thoughtful gift-giver! We'd love to have you try our newest Berry Bliss scent.",
    helpfulCount: 47,
    verified: true,
    tags: ['packaging', 'scent', 'moisturizing', 'gift']
  },
  {
    id: '2',
    customerName: 'Marcus Johnson',
    customerAvatar: '',
    initials: 'MJ',
    product: 'Power Mist - Rainwater',
    platform: 'Amazon',
    country: 'United States',
    rating: 4,
    date: '2024-01-14',
    text: "Good product overall. The Rainwater scent is clean and fresh — not too overpowering. My only complaint is that the pump occasionally gets stuck. But the formula itself is great: non-sticky, fast absorbing.",
    aiSummary: 'Generally positive with minor product quality issue around pump mechanism. Praises formula effectiveness.',
    emotion: 'Satisfied',
    sentiment: 'Positive',
    suggestedResponse: "Hi Marcus, thanks for the honest review! We're sorry to hear about the pump issue — that's definitely not the experience we want for you. Please reach out to our support team and we'll send you a replacement. So glad you love the Rainwater scent!",
    helpfulCount: 23,
    verified: true,
    tags: ['pump issue', 'scent', 'formula', 'fast-absorbing']
  },
  {
    id: '3',
    customerName: 'Emma Rodriguez',
    customerAvatar: '',
    initials: 'ER',
    product: 'Power Mist - Berry Bliss',
    platform: 'Target',
    country: 'United States',
    rating: 5,
    date: '2024-01-13',
    text: "Berry Bliss is my absolute obsession! The color of the bottle matches the scent perfectly. I keep one on my nightstand, one in my car, and one at work. People always compliment me when I use it. Worth every penny!",
    aiSummary: 'High emotional attachment, repeat purchase intent, social proof through compliments. Strong loyalty indicators.',
    emotion: 'Excited',
    sentiment: 'Positive',
    suggestedResponse: "You're making us blush, Emma! 🫐 Berry Bliss fans are truly our favorites. The fact that you keep 3 bottles means the world to us. Tag us @touchland — we'd love to see your collection!",
    helpfulCount: 38,
    verified: true,
    tags: ['loyalty', 'multiple purchase', 'social proof', 'packaging']
  },
  {
    id: '4',
    customerName: 'David Kim',
    customerAvatar: '',
    initials: 'DK',
    product: 'Power Mist - Peachy Lychee',
    platform: 'Google',
    country: 'Canada',
    rating: 3,
    date: '2024-01-12',
    text: "The scent is nice but fades too quickly. After about 10 minutes I can't smell it anymore. For the price point I expected the scent to last longer. The sanitizing effect seems fine. Would be 5 stars if the scent lasted.",
    aiSummary: 'Mixed review centered on fragrance longevity. Price-value mismatch perception. Core sanitizing function is satisfactory.',
    emotion: 'Neutral',
    sentiment: 'Neutral',
    suggestedResponse: "Thank you for your candid feedback, David! Fragrance longevity is something we take seriously. Our scents are designed to be light and skin-safe, but we hear your feedback. Try applying to pulse points for longer-lasting scent. We'd love to send you our Vanilla Blossom — our longest-lasting scent!",
    helpfulCount: 15,
    verified: false,
    tags: ['scent longevity', 'price-value', 'fragrance']
  },
  {
    id: '5',
    customerName: 'Priya Patel',
    customerAvatar: '',
    initials: 'PP',
    product: 'Power Mist - Vanilla Blossom',
    platform: 'Ulta',
    country: 'United States',
    rating: 5,
    date: '2024-01-11',
    text: "I've been a Touchland customer for 3 years and they just keep getting better. Vanilla Blossom is warm, sophisticated, and the bottle design is stunning. My teenager stole mine the second I brought it home! Ordering 10 more as gifts.",
    aiSummary: 'Long-term loyal customer, high gift purchase intent, cross-generational appeal demonstrated. Excellent brand ambassador.',
    emotion: 'Happy',
    sentiment: 'Positive',
    suggestedResponse: "Three years with us — you're basically family, Priya! 🌸 We're so happy Vanilla Blossom is winning over your whole household. Your teenager has great taste! Consider our bundle packs for gifting season — perfect for a multi-bottle order.",
    helpfulCount: 62,
    verified: true,
    tags: ['loyalty', 'gift', 'family', 'design']
  },
  {
    id: '6',
    customerName: 'Jason Williams',
    customerAvatar: '',
    initials: 'JW',
    product: 'Power Mist - Wild Watermelon',
    platform: 'Amazon',
    country: 'United States',
    rating: 2,
    date: '2024-01-10',
    text: "Received a bottle where the pump was completely broken and not usable. Had to return it. The replacement worked fine but the whole experience was frustrating. Also think the bottle is too small for the price.",
    aiSummary: 'Product quality/packaging issue causing negative experience. Price-to-size concern. Fulfilled replacement suggests recoverable relationship.',
    emotion: 'Frustrated',
    sentiment: 'Negative',
    suggestedResponse: "Jason, we sincerely apologize for the broken pump on your first bottle — that's completely unacceptable. We're glad the replacement worked, but we know the hassle isn't worth it. Please use code JASON15 for 15% off your next order as our apology. Your feedback helps us improve quality control.",
    helpfulCount: 28,
    verified: true,
    tags: ['defective product', 'pump broken', 'return', 'price-value']
  },
  {
    id: '7',
    customerName: 'Aisha Thompson',
    customerAvatar: '',
    initials: 'AT',
    product: 'Power Mist - Aloe You',
    platform: 'Sephora',
    country: 'United Kingdom',
    rating: 5,
    date: '2024-01-09',
    text: "As someone with very sensitive skin, finding a hand sanitizer that doesn't irritate is nearly impossible. Touchland Aloe You is a miracle product. Zero irritation, smells amazing, and actually moisturizes. I've recommended it to everyone in my skincare community.",
    aiSummary: 'Sensitive skin testimonial — high value segment. Strong community advocacy. Highlights differentiated moisturizing and skin-safe formula.',
    emotion: 'Happy',
    sentiment: 'Positive',
    suggestedResponse: "Your review means so much, Aisha! 🌿 Sensitive skin community members are exactly who we designed Aloe You for. Thank you for sharing with your skincare community — we'd love to connect with you. Have you seen our skincare collaboration coming next season?",
    helpfulCount: 71,
    verified: true,
    tags: ['sensitive skin', 'skincare', 'community', 'moisturizing']
  },
  {
    id: '8',
    customerName: 'Carlos Mendez',
    customerAvatar: '',
    initials: 'CM',
    product: 'Power Mist - Peachy Lychee',
    platform: 'Target',
    country: 'Mexico',
    rating: 4,
    date: '2024-01-08',
    text: "Compré esto como regalo y a todos les encantó. El aroma durazno-lychee es muy original y diferente a lo que existe en el mercado. El envase es hermoso. Solo resta que sea más económico.",
    aiSummary: 'Gift purchase from international market. Unique scent differentiator acknowledged. Price sensitivity noted. Product appeals across cultures.',
    emotion: 'Satisfied',
    sentiment: 'Positive',
    suggestedResponse: "¡Muchas gracias, Carlos! Nos alegra que el regalo fue todo un éxito. Peachy Lychee es definitivamente uno de nuestros sabores más únicos. Estamos trabajando en opciones más accesibles para el mercado latinoamericano. ¡Gracias por tu apoyo!",
    helpfulCount: 19,
    verified: true,
    tags: ['international', 'gift', 'unique scent', 'price']
  }
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Power Mist — Wild Watermelon',
    tagline: 'Summer in every spray',
    price: 14.99,
    revenue: 842000,
    revenueChange: 23.4,
    sentiment: 94,
    mentions: 12840,
    mentionsChange: 43.2,
    reviews: 4821,
    rating: 4.8,
    inventory: 18420,
    trend: [65, 72, 68, 85, 92, 88, 95, 102, 98, 115, 128, 134],
    aiRecommendation: 'Trending on TikTok — increase ad spend by 30% to capitalize on viral momentum. Consider limited summer packaging.',
    color: '#FF6B6B',
    image: '',
    category: 'Hand Sanitizer',
    sku: 'TL-WW-001'
  },
  {
    id: '2',
    name: 'Power Mist — Berry Bliss',
    tagline: 'Sweet berry euphoria',
    price: 14.99,
    revenue: 634000,
    revenueChange: 12.1,
    sentiment: 91,
    mentions: 8320,
    mentionsChange: 18.7,
    reviews: 3614,
    rating: 4.7,
    inventory: 14280,
    trend: [55, 58, 62, 70, 68, 74, 78, 82, 79, 86, 90, 88],
    aiRecommendation: 'Strong growth trajectory. Bundle with Wild Watermelon for summer promotion. Influencer gifting recommended.',
    color: '#C678DD',
    image: '',
    category: 'Hand Sanitizer',
    sku: 'TL-BB-002'
  },
  {
    id: '3',
    name: 'Power Mist — Peachy Lychee',
    tagline: 'Exotic fruit freshness',
    price: 14.99,
    revenue: 521000,
    revenueChange: 8.4,
    sentiment: 88,
    mentions: 6150,
    mentionsChange: 9.2,
    reviews: 2891,
    rating: 4.6,
    inventory: 11640,
    trend: [48, 52, 50, 58, 55, 62, 60, 65, 68, 72, 70, 74],
    aiRecommendation: 'Opportunity in Asian markets. Consider localized TikTok campaign for Southeast Asian demographic.',
    color: '#FF9F43',
    image: '',
    category: 'Hand Sanitizer',
    sku: 'TL-PL-003'
  },
  {
    id: '4',
    name: 'Power Mist — Rainwater',
    tagline: 'Pure, clean, refreshing',
    price: 14.99,
    revenue: 478000,
    revenueChange: -2.1,
    sentiment: 85,
    mentions: 5240,
    mentionsChange: -5.4,
    reviews: 2432,
    rating: 4.5,
    inventory: 9820,
    trend: [62, 58, 55, 52, 50, 48, 46, 44, 45, 43, 42, 40],
    aiRecommendation: 'Declining trend — needs refreshed marketing. Consider fall/winter positioning campaign with new photography.',
    color: '#74B9FF',
    image: '',
    category: 'Hand Sanitizer',
    sku: 'TL-RW-004'
  },
  {
    id: '5',
    name: 'Power Mist — Vanilla Blossom',
    tagline: 'Warm & sophisticated',
    price: 14.99,
    revenue: 712000,
    revenueChange: 16.8,
    sentiment: 96,
    mentions: 9870,
    mentionsChange: 31.4,
    reviews: 4120,
    rating: 4.9,
    inventory: 16500,
    trend: [58, 62, 68, 74, 80, 86, 90, 94, 98, 104, 112, 118],
    aiRecommendation: 'Top performer in Q4 gifting season. Launch holiday limited edition packaging to maximize seasonal revenue.',
    color: '#FFEAA7',
    image: '',
    category: 'Hand Sanitizer',
    sku: 'TL-VB-005'
  },
  {
    id: '6',
    name: 'Power Mist — Aloe You',
    tagline: 'Gentle on sensitive skin',
    price: 16.99,
    revenue: 398000,
    revenueChange: 28.3,
    sentiment: 97,
    mentions: 7640,
    mentionsChange: 52.1,
    reviews: 1982,
    rating: 4.9,
    inventory: 8240,
    trend: [30, 38, 45, 52, 60, 68, 72, 80, 88, 98, 110, 124],
    aiRecommendation: 'Fastest growing SKU. Strong dermatologist endorsement opportunity. Target skincare influencer tier.',
    color: '#55EFC4',
    image: '',
    category: 'Hand Sanitizer',
    sku: 'TL-AY-006'
  }
]

export const influencers: Influencer[] = [
  {
    id: '1',
    name: 'Jade Morrison',
    handle: '@jademorrison',
    avatar: '',
    initials: 'JM',
    platform: 'TikTok',
    followers: 2840000,
    engagement: 8.4,
    audienceMatch: 94,
    category: 'Beauty & Skincare',
    location: 'Los Angeles, CA',
    campaignROI: 4.8,
    compatibilityScore: 97,
    suggestedPartnership: 'Sponsored series: "My Daily Refresh Routine" featuring Wild Watermelon & Vanilla Blossom for summer/fall transition.',
    recentPost: 'Testing viral hand sanitizers so you don\'t have to ✨',
    avgViews: 840000,
    price: 8500,
    tags: ['skincare', 'beauty', 'luxury', 'trending']
  },
  {
    id: '2',
    name: 'Tyler Kwon',
    handle: '@tylerkwon',
    avatar: '',
    initials: 'TK',
    platform: 'Instagram',
    followers: 1240000,
    engagement: 6.2,
    audienceMatch: 88,
    category: 'Lifestyle & Wellness',
    location: 'New York, NY',
    campaignROI: 3.9,
    compatibilityScore: 91,
    suggestedPartnership: 'Office & travel essentials integration. Target his professional millennial audience with Rainwater and Berry Bliss.',
    recentPost: 'My work-from-anywhere essentials 🌍',
    avgViews: 284000,
    price: 4200,
    tags: ['wellness', 'travel', 'lifestyle', 'professional']
  },
  {
    id: '3',
    name: 'Zara Ali',
    handle: '@zaraali_beauty',
    avatar: '',
    initials: 'ZA',
    platform: 'YouTube',
    followers: 840000,
    engagement: 11.2,
    audienceMatch: 96,
    category: 'Skincare & Clean Beauty',
    location: 'London, UK',
    campaignROI: 5.2,
    compatibilityScore: 95,
    suggestedPartnership: 'Dedicated "Clean Beauty Essentials" video. Sensitive skin angle with Aloe You. Target UK and EU expansion.',
    recentPost: 'The ONLY hand sanitizers I trust for sensitive skin',
    avgViews: 420000,
    price: 6800,
    tags: ['clean beauty', 'sensitive skin', 'UK', 'youtube']
  },
  {
    id: '4',
    name: 'Maya Patel',
    handle: '@mayaxbeauty',
    avatar: '',
    initials: 'MP',
    platform: 'TikTok',
    followers: 5210000,
    engagement: 9.8,
    audienceMatch: 92,
    category: 'Luxury Beauty',
    location: 'Miami, FL',
    campaignROI: 6.1,
    compatibilityScore: 93,
    suggestedPartnership: 'Luxury unboxing series. Launch partnership with limited-edition Peachy Lychee bundle. Peak summer campaign.',
    recentPost: 'Rating luxury hand care products 💅',
    avgViews: 1820000,
    price: 15000,
    tags: ['luxury', 'unboxing', 'beauty', 'miami']
  },
  {
    id: '5',
    name: 'Damien Frost',
    handle: '@damienfrost',
    avatar: '',
    initials: 'DF',
    platform: 'Instagram',
    followers: 620000,
    engagement: 7.4,
    audienceMatch: 82,
    category: 'Menswear & Grooming',
    location: 'Chicago, IL',
    campaignROI: 3.2,
    compatibilityScore: 84,
    suggestedPartnership: 'Grooming & self-care angle. Target male demographic with Rainwater scent. Gym bag essentials format.',
    recentPost: 'Men\'s grooming essentials that actually work',
    avgViews: 124000,
    price: 2800,
    tags: ['mens', 'grooming', 'gym', 'lifestyle']
  },
  {
    id: '6',
    name: 'Ariana Luz',
    handle: '@arianaluz',
    avatar: '',
    initials: 'AL',
    platform: 'TikTok',
    followers: 3680000,
    engagement: 12.4,
    audienceMatch: 98,
    category: 'Beauty & Self-Care',
    location: 'São Paulo, Brazil',
    campaignROI: 7.2,
    compatibilityScore: 99,
    suggestedPartnership: 'LATAM expansion ambassador. Berry Bliss & Peachy Lychee campaign. Spanish/Portuguese bilingual content.',
    recentPost: 'Self-care products that smell like heaven 🌺',
    avgViews: 2140000,
    price: 12000,
    tags: ['brazil', 'latam', 'beauty', 'bilingual', 'top-tier']
  }
]

export const competitors: Competitor[] = [
  {
    id: '1',
    name: 'Touchland',
    logo: '🍉',
    marketShare: 34.2,
    marketShareChange: 4.8,
    sentiment: 91,
    avgRating: 4.7,
    totalReviews: 48200,
    priceRange: '$14.99 - $16.99',
    strengths: ['Premium design', 'Viral TikTok presence', 'Moisturizing formula', 'Beautiful packaging', 'Gift market'],
    weaknesses: ['Premium price point', 'Limited distribution', 'Small bottle size'],
    recentActivity: 'Launched Aloe You SKU with 52% above-average growth'
  },
  {
    id: '2',
    name: 'Purell',
    logo: '💙',
    marketShare: 41.8,
    marketShareChange: -2.1,
    sentiment: 68,
    avgRating: 4.1,
    totalReviews: 284000,
    priceRange: '$3.99 - $12.99',
    strengths: ['Mass market distribution', 'Brand recognition', 'Price accessibility', 'Healthcare endorsement'],
    weaknesses: ['Dry/harsh formula', 'No fragrance appeal', 'Clinical/generic packaging', 'No premium tier'],
    recentActivity: 'Launched moisturizing line to compete with premium brands'
  },
  {
    id: '3',
    name: 'Dr. Bronner\'s',
    logo: '🌿',
    marketShare: 12.4,
    marketShareChange: 1.2,
    sentiment: 82,
    avgRating: 4.4,
    totalReviews: 62000,
    priceRange: '$8.99 - $19.99',
    strengths: ['Organic positioning', 'Loyal eco-conscious base', 'Multiple product lines', 'Ethical brand story'],
    weaknesses: ['Niche appeal', 'Limited trendy factor', 'Distribution challenges', 'No viral marketing'],
    recentActivity: 'Expanded into premium personal care with new foaming gel line'
  },
  {
    id: '4',
    name: 'EO Products',
    logo: '🌸',
    marketShare: 8.1,
    marketShareChange: 0.6,
    sentiment: 79,
    avgRating: 4.3,
    totalReviews: 28400,
    priceRange: '$7.99 - $15.99',
    strengths: ['Essential oil ingredients', 'Natural/clean positioning', 'Good scent variety', 'Eco packaging'],
    weaknesses: ['Low brand awareness', 'Minimal social presence', 'No viral products', 'Generic design'],
    recentActivity: 'Partnership with Whole Foods for expanded shelf placement'
  }
]

export const socialPosts: SocialPost[] = [
  {
    id: '1',
    platform: 'TikTok',
    author: 'Jade Morrison',
    authorHandle: '@jademorrison',
    avatar: '',
    initials: 'JM',
    content: 'POV: you discover the most aesthetic hand sanitizer and now you cant stop buying every flavor 🍉✨ #Touchland #HandSanitizer #AestheticBeauty #SkincareTok',
    hashtags: ['Touchland', 'HandSanitizer', 'AestheticBeauty', 'SkincareTok'],
    likes: 284000,
    comments: 8420,
    shares: 42000,
    reach: 1820000,
    sentiment: 'Positive',
    date: '2024-01-15',
    url: '#',
    mediaType: 'video'
  },
  {
    id: '2',
    platform: 'Instagram',
    author: 'Wellness Daily',
    authorHandle: '@wellnessdaily',
    avatar: '',
    initials: 'WD',
    content: 'Our current desk aesthetic ✨ Touchland Vanilla Blossom is giving everything. The scent, the look, the feel — literally unmatched. What\'s your current fave? 🌸',
    hashtags: ['DeskSetup', 'Touchland', 'VanillaBlossom', 'WorkplaceWellness'],
    likes: 42800,
    comments: 1240,
    shares: 3800,
    reach: 284000,
    sentiment: 'Positive',
    date: '2024-01-14',
    url: '#',
    mediaType: 'image'
  },
  {
    id: '3',
    platform: 'Twitter',
    author: 'BeautyEditor',
    authorHandle: '@beautyeditor_ny',
    avatar: '',
    initials: 'BE',
    content: 'hot take: Touchland Berry Bliss is the only acceptable hand sanitizer to use on a first date. the scent says "i have my life together" without being overwhelming.',
    hashtags: ['Touchland', 'BeautyTips', 'HandCare'],
    likes: 12400,
    comments: 842,
    shares: 2840,
    reach: 84000,
    sentiment: 'Positive',
    date: '2024-01-13',
    url: '#',
    mediaType: 'text'
  },
  {
    id: '4',
    platform: 'Reddit',
    author: 'u/skincarenerd42',
    authorHandle: 'u/skincarenerd42',
    avatar: '',
    initials: 'SN',
    content: '[Review] Been using Touchland Aloe You for 6 months with rosacea and it\'s the only sanitizer that doesn\'t flare me up. Ingredients are clean, scent is mild, formula is genuinely moisturizing. Game changer for sensitive skin people.',
    hashtags: ['Skincare', 'Rosacea', 'HandSanitizer', 'SensitiveSkin'],
    likes: 4820,
    comments: 284,
    shares: 820,
    reach: 48200,
    sentiment: 'Positive',
    date: '2024-01-12',
    url: '#',
    mediaType: 'text'
  },
  {
    id: '5',
    platform: 'TikTok',
    author: 'Maya Patel',
    authorHandle: '@mayaxbeauty',
    avatar: '',
    initials: 'MP',
    content: 'Ranking ALL the Touchland flavors from worst to best 🌸🍑🍇🍉💦 which one would you choose? #Touchland #PowerMist #BeautyTok #Ranking',
    hashtags: ['Touchland', 'PowerMist', 'BeautyTok', 'Ranking'],
    likes: 521000,
    comments: 18400,
    shares: 84000,
    reach: 4200000,
    sentiment: 'Positive',
    date: '2024-01-11',
    url: '#',
    mediaType: 'video'
  },
  {
    id: '6',
    platform: 'Facebook',
    author: 'Clean Beauty Mom',
    authorHandle: '@cleanbeautymom',
    avatar: '',
    initials: 'CB',
    content: 'Honest review: switched my whole family to Touchland after my daughter had reactions to every other brand. 3 months in — no reactions, beautiful scents, and my husband even uses it without complaint! The Rainwater is his fave.',
    hashtags: ['CleanBeauty', 'FamilySkincare', 'Touchland', 'KidSafe'],
    likes: 8240,
    comments: 642,
    shares: 1840,
    reach: 62000,
    sentiment: 'Positive',
    date: '2024-01-10',
    url: '#',
    mediaType: 'text'
  },
  {
    id: '7',
    platform: 'YouTube',
    author: 'Zara Ali',
    authorHandle: '@zaraali_beauty',
    avatar: '',
    initials: 'ZA',
    content: 'HONEST REVIEW: I tested every Touchland formula on my sensitive skin so you don\'t have to. Results shocked me... | Clean Beauty Deep Dive',
    hashtags: ['HonestReview', 'SensitiveSkin', 'Touchland', 'CleanBeauty'],
    likes: 28400,
    comments: 2140,
    shares: 4820,
    reach: 420000,
    sentiment: 'Positive',
    date: '2024-01-09',
    url: '#',
    mediaType: 'video'
  },
  {
    id: '8',
    platform: 'LinkedIn',
    author: 'Retail Trends Weekly',
    authorHandle: 'Retail Trends Weekly',
    avatar: '',
    initials: 'RT',
    content: 'Touchland is redefining the $4.2B hand sanitizer market with premium design-first positioning. Their TikTok-native strategy has driven 340% YoY social mentions growth. Case study of how beauty-adjacent wellness brands win Gen Z loyalty.',
    hashtags: ['RetailTrends', 'BrandStrategy', 'Touchland', 'GenZMarketing'],
    likes: 4280,
    comments: 284,
    shares: 1240,
    reach: 84000,
    sentiment: 'Positive',
    date: '2024-01-08',
    url: '#',
    mediaType: 'text'
  }
]

export const notifications: Notification[] = [
  {
    id: '1',
    type: 'alert',
    title: 'Wild Watermelon trending on TikTok',
    description: 'Detected 43% spike in mentions in the last 6 hours. 3 viral videos exceeding 500K views.',
    time: '2 minutes ago',
    read: false,
    priority: 'high',
    icon: 'trending-up'
  },
  {
    id: '2',
    type: 'insight',
    title: 'AI Insight: Competitor alert',
    description: 'Purell launched a new moisturizing formula. Sentiment analysis suggests weak consumer reception.',
    time: '18 minutes ago',
    read: false,
    priority: 'high',
    icon: 'brain'
  },
  {
    id: '3',
    type: 'mention',
    title: 'New mention from verified influencer',
    description: '@mayaxbeauty (5.2M followers) posted a Touchland ranking video. 521K likes and counting.',
    time: '1 hour ago',
    read: false,
    priority: 'high',
    icon: 'at-sign'
  },
  {
    id: '4',
    type: 'report',
    title: 'Weekly Performance Report Ready',
    description: 'Your weekly brand intelligence report is ready. Overall sentiment: 91% positive.',
    time: '3 hours ago',
    read: false,
    priority: 'medium',
    icon: 'file-text'
  },
  {
    id: '5',
    type: 'alert',
    title: 'Inventory alert: Aloe You',
    description: 'Aloe You is approaching reorder threshold (8,240 units remaining). Demand forecast shows 12-day runway.',
    time: '5 hours ago',
    read: true,
    priority: 'medium',
    icon: 'package'
  },
  {
    id: '6',
    type: 'campaign',
    title: 'Campaign milestone reached',
    description: 'Berry Bliss summer campaign hit 10M impressions. ROI currently at 4.2x projected.',
    time: '8 hours ago',
    read: true,
    priority: 'medium',
    icon: 'zap'
  },
  {
    id: '7',
    type: 'mention',
    title: '47 new reviews this morning',
    description: 'Average rating: 4.8 ⭐. 43 positive, 3 neutral, 1 negative. AI responses prepared.',
    time: '12 hours ago',
    read: true,
    priority: 'low',
    icon: 'star'
  },
  {
    id: '8',
    type: 'insight',
    title: 'Seasonal opportunity detected',
    description: 'AI detected Valentine\'s Day gifting keyword surge. Recommend launching gift bundle campaign within 72 hours.',
    time: '1 day ago',
    read: true,
    priority: 'medium',
    icon: 'gift'
  }
]

export const aiRecommendations: AIRecommendation[] = [
  {
    id: '1',
    category: 'Marketing',
    title: 'Launch TikTok Creator Fund Campaign for Wild Watermelon',
    description: 'Wild Watermelon is showing viral indicators (43% mention spike, multiple 500K+ videos). Now is the optimal window to amplify with paid creator partnerships before organic momentum fades.',
    priority: 'Critical',
    difficulty: 'Easy',
    impact: 94,
    roi: '$8.4 per $1 spent',
    confidence: 96,
    timeline: '72 hours',
    actionSteps: [
      'Identify 10-15 micro influencers (100K-500K) in beauty/skincare',
      'Create $25,000 creator fund with $500-2,500 per creator',
      'Brief: authentic "first reaction" format',
      'Target trending sounds and hashtags',
      'Track with UTM codes for ROI measurement'
    ],
    expectedOutcome: 'Estimated 8-12M additional impressions and 15-25% sales lift within 2 weeks'
  },
  {
    id: '2',
    category: 'Product',
    title: 'Accelerate Aloe You Inventory Replenishment',
    description: 'Aloe You has only 12 days of supply remaining at current sell-through rate. The product is growing 52% above forecast, driven by sensitive skin community adoption.',
    priority: 'Critical',
    difficulty: 'Medium',
    impact: 88,
    roi: '$2.1M prevented revenue loss',
    confidence: 99,
    timeline: '48 hours',
    actionSteps: [
      'Emergency PO for 30,000 units (2x normal order)',
      'Negotiate expedited production timeline with supplier',
      'Set up waitlist on website to capture demand',
      'Alert retail partners of potential short supply',
      'Consider temporary price hold to prevent channel conflict'
    ],
    expectedOutcome: 'Prevent stockout, capture $2.1M in at-risk revenue, maintain retail partner relationships'
  },
  {
    id: '3',
    category: 'Content',
    title: 'Create Sensitive Skin Testimonial Content Series',
    description: 'Reddit and Sephora reviews reveal strong sensitive skin segment. This underserved audience has high purchasing intent and peer influence. Aloe You has a 97% sentiment score with this segment.',
    priority: 'High',
    difficulty: 'Easy',
    impact: 78,
    roi: '3.8x estimated',
    confidence: 88,
    timeline: '1-2 weeks',
    actionSteps: [
      'Partner with 3-5 dermatology-focused influencers',
      'Create "Dermatologist Tested" content series',
      'Develop sensitive skin landing page with ingredient transparency',
      'Submit for allergy/dermatologist testing certification',
      'Run targeted ads on skincare subreddits and communities'
    ],
    expectedOutcome: '35% increase in Aloe You awareness, entry into medical/clinical recommendation channel'
  },
  {
    id: '4',
    category: 'Pricing',
    title: 'Launch Valentine\'s Day Gift Bundle at $39.99',
    description: 'AI detected 340% increase in gift-related keywords for hand sanitizers. Bundle opportunity with premium packaging can capture gifting market at 2.8x unit economics vs. single product.',
    priority: 'High',
    difficulty: 'Medium',
    impact: 82,
    roi: '2.8x unit economics',
    confidence: 91,
    timeline: '10 days',
    actionSteps: [
      'Bundle: Berry Bliss + Vanilla Blossom + Peachy Lychee in gift box',
      'Design limited-edition Valentine\'s packaging',
      'Price at $39.99 (vs. $44.97 individual)',
      'Promote as "The Perfect Gift" across all channels',
      'Launch on all retail channels + website'
    ],
    expectedOutcome: 'Estimated $420K incremental revenue in 2-week Valentine\'s window'
  },
  {
    id: '5',
    category: 'Marketing',
    title: 'Revitalize Rainwater with "Clean Slate" Campaign',
    description: 'Rainwater is the only declining SKU (-2.1% revenue, -5.4% mentions). Product quality is strong (4.5 stars) but marketing is stale. A fresh creative direction can reverse the trend.',
    priority: 'Medium',
    difficulty: 'Hard',
    impact: 65,
    roi: '2.1x estimated',
    confidence: 74,
    timeline: '3-4 weeks',
    actionSteps: [
      'Commission new lifestyle photography (minimalist, zen aesthetic)',
      'Reposition as "mindfulness & clean living" product',
      'Partner with yoga, meditation, wellness influencers',
      'Create "Clean Slate Challenge" on TikTok',
      'Feature in "New Year, New You" editorial placements'
    ],
    expectedOutcome: 'Stabilize revenue decline, target 8-12% growth rebound within 60 days'
  },
  {
    id: '6',
    category: 'Sales',
    title: 'Expand UK/EU Distribution via Aisha Thompson Partnership',
    description: 'Aisha Thompson (UK-based, 840K YouTube subscribers) organic review generated 71 "helpful" votes and significant UK traffic. UK market shows 28% untapped demand for premium hand sanitizer.',
    priority: 'Medium',
    difficulty: 'Hard',
    impact: 72,
    roi: '$1.2M 12-month revenue potential',
    confidence: 82,
    timeline: '6-8 weeks',
    actionSteps: [
      'Negotiate UK ambassador deal with Zara Ali',
      'Partner with Boots, Selfridges for UK retail placement',
      'Localize website for GBP pricing and UK shipping',
      'Adapt marketing copy for UK/EU sensibilities',
      'File EU cosmetics compliance documentation'
    ],
    expectedOutcome: '$1.2M first-year UK revenue, establishes European market entry foundation'
  }
]

export const chartData = {
  reviewTrends: [
    { month: 'Aug', positive: 2840, neutral: 420, negative: 180 },
    { month: 'Sep', positive: 3120, neutral: 380, negative: 160 },
    { month: 'Oct', positive: 3680, neutral: 440, negative: 220 },
    { month: 'Nov', positive: 4210, neutral: 520, negative: 280 },
    { month: 'Dec', positive: 5840, neutral: 620, negative: 340 },
    { month: 'Jan', positive: 6420, neutral: 580, negative: 290 }
  ],
  revenueTrends: [
    { month: 'Aug', revenue: 2840000, target: 2500000 },
    { month: 'Sep', revenue: 3120000, target: 2800000 },
    { month: 'Oct', revenue: 3580000, target: 3200000 },
    { month: 'Nov', revenue: 4820000, target: 4000000 },
    { month: 'Dec', revenue: 6240000, target: 5000000 },
    { month: 'Jan', revenue: 5120000, target: 4800000 }
  ],
  sentimentTimeline: [
    { week: 'W1', touchland: 88, purell: 64, drbronner: 78 },
    { week: 'W2', touchland: 90, purell: 66, drbronner: 79 },
    { week: 'W3', touchland: 87, purell: 62, drbronner: 80 },
    { week: 'W4', touchland: 92, purell: 68, drbronner: 82 },
    { week: 'W5', touchland: 91, purell: 65, drbronner: 81 },
    { week: 'W6', touchland: 94, purell: 70, drbronner: 83 }
  ],
  socialMentions: [
    { day: 'Mon', instagram: 840, tiktok: 2840, twitter: 420, reddit: 180 },
    { day: 'Tue', instagram: 920, tiktok: 3120, twitter: 480, reddit: 210 },
    { day: 'Wed', instagram: 780, tiktok: 2680, twitter: 380, reddit: 160 },
    { day: 'Thu', instagram: 1040, tiktok: 3840, twitter: 520, reddit: 240 },
    { day: 'Fri', instagram: 1280, tiktok: 5210, twitter: 680, reddit: 320 },
    { day: 'Sat', instagram: 1640, tiktok: 7840, twitter: 840, reddit: 480 },
    { day: 'Sun', instagram: 1420, tiktok: 6420, twitter: 720, reddit: 420 }
  ],
  marketShare: [
    { name: 'Touchland', value: 34.2, fill: 'var(--chart-1)' },
    { name: 'Purell', value: 41.8, fill: 'var(--chart-3)' },
    { name: 'Dr. Bronner\'s', value: 12.4, fill: 'var(--chart-2)' },
    { name: 'EO Products', value: 8.1, fill: 'var(--chart-4)' },
    { name: 'Others', value: 3.5, fill: 'var(--chart-5)' }
  ],
  weeklyGrowth: [
    { week: 'W1', growth: 12 },
    { week: 'W2', growth: 18 },
    { week: 'W3', growth: 14 },
    { week: 'W4', growth: 22 },
    { week: 'W5', growth: 28 },
    { week: 'W6', growth: 24 }
  ]
}

export const stats = {
  totalReviews: { value: 48200, change: 12.4, label: 'Total Reviews' },
  avgRating: { value: 4.7, change: 0.2, label: 'Avg Rating' },
  sentiment: { value: 91, change: 8.3, label: 'Sentiment Score' },
  revenue: { value: 3584200, change: 18.2, label: 'Monthly Revenue' },
  socialMentions: { value: 284000, change: 43.2, label: 'Social Mentions' },
  returningCustomers: { value: 67.4, change: 5.8, label: 'Returning Customers' },
  conversionRate: { value: 4.8, change: 1.2, label: 'Conversion Rate' },
  influencerReach: { value: 28400000, change: 31.4, label: 'Influencer Reach' }
}
